name: Type Check

on:
  push:
    branches: [develop, main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: pnpm install

      - name: Run type check
        run: pnpm typecheck
