name: CI/CD Pipeline

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
      - run: pnpm install
      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
      - run: pnpm install
      - run: pnpm typecheck

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.6.3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.19.0
      - run: pnpm install

      - name: Setup environment
        run: |
          echo "Creating .env.development file"
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/flaira?schema=public" > .env.development
          # Add other necessary env variables here

      - name: Start PostgreSQL
        run: |
          # Start PostgreSQL
          pnpm run services:up
          echo "Docker containers status:"
          docker ps

      - name: Initialize PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to initialize..."
          # Wait for PostgreSQL to be fully available
          sleep 15
          # Create database if it doesn't exist
          docker exec postgres_dev psql -U postgres -c "CREATE DATABASE flaira;" || echo "Database already exists"
          # Run any migrations if needed
          echo "Running migrations..."
          pnpm --filter @flaira/backend run migrate:deploy || echo "No migrations to run"

      - name: Start backend
        run: |
          # Start the backend service with nohup to ensure it stays running
          echo "Starting backend service..."
          nohup pnpm run dev:backend > backend.log 2>&1 &
          # Wait for the backend to initialize
          sleep 15

      - name: Wait for backend with OK status
        run: |
          echo "Checking if backend is running with OK status..."
          max_attempts=12
          attempts=0
          
          while [ $attempts -lt $max_attempts ]; do
            response=$(curl -s http://localhost:3001/status)
            echo "Response: $response"
            
            if echo "$response" | grep -q '"status":"ok"'; then
              echo "Backend is up and running with OK status!"
              break
            fi
            
            attempts=$((attempts + 1))
            echo "Attempt $attempts/$max_attempts: Backend not ready yet, waiting..."
            
            # Print container logs for debugging
            if [ $attempts -eq 5 ]; then
              echo "Backend still not ready, checking container logs:"
              docker logs postgres_dev
              echo "Backend logs:"
              cat backend.log
            fi
            
            sleep 10
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Backend did not return OK status within the timeout period." >&2
            docker logs postgres_dev
            cat backend.log
            exit 1
          fi

      - name: Run tests
        run: VITEST_LOG_LEVEL=verbose pnpm test

      - name: Check backend logs
        if: always()
        run: |
          echo "Backend logs:"
          cat backend.log

  build-and-push:
    needs: [lint, typecheck, tests]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.6.3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: pnpm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::692859947277:role/GitHubActionsECRPushRole
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        run: |
          IMAGE_TAG=latest
          REPO=692859947277.dkr.ecr.us-east-2.amazonaws.com/flaira
          docker build -t $REPO:$IMAGE_TAG .
          docker push $REPO:$IMAGE_TAG

      - name: Force ECS to redeploy latest image
        run: |
          aws ecs update-service \
            --cluster flaira \
            --service flairaprod \
            --force-new-deployment